---
title: "About Me"
output: 
  html_document:
    toc: true
    toc_float: true
---
<font size="5">Professional Experiences</font>

<span class="test">
<p style="font-size: large; float: left; display: inline-block;">Pfizer Inc.</p >
<p style="float: right; display: inline-block;">07-8/2019|Shanghai, China</p ></span>

<br><br>
<p style="font-family: times, serif; font-size:11pt; font-style:italic;>Commercial Access Assistant</p>
<ul>
<li>Planned logistics for Pfizer and GSK merger for a Press Conference to market and promote health care products for 500 company employees</li>
<li>Led and managed 6 interns in the commercial access department to communicate with other division to provide products to display during press conference</li>
<li>Evaluated advertisement slogan to ensure compliance with government requirements which was successfully approved</li>
<li>Devised a new database system to create a monthly budget for parcel delivery fees to reduce costs by 6%</li>
</ul>


<span class="test">
<p style="font-size: large; float: left; display: inline-block;">ECOMICROWAVE (medical instrument producer) </p >
<p style="float: right; display: inline-block;">07-08/2018|Nanjing, China</p ></span>
<br/><br>
<p style="font-family: times, serif; font-size:11pt; font-style:italic;>Data Analyst, Marketing Department</p>
<ul>
<li>Conducted data analysis and non-inferiority test to verify the treatment effect for the instruments and others on the market </li>
<li>Engaged in comparison research on the effect of microwave and radio frequency on treating varicosity in order to verify that the effect of microwave equaled that of the radio frequency </li>
<li>Designed and patented, with the research team, a pillbox that can offer automatic dispense and prevent medicine from being contaminated (Patent Registration Number:201821817693.3) </li>
</ul>


<span class="test">
<p style="font-size: large; float: left; display: inline-block;">Tigress Financial Partners </p >
<p style="float: right; display: inline-block;">06-07/2017|New York, NY</p ></span>

<br><br>
<p style="font-family: times, serif; font-size:11pt; font-style:italic;>Investment Banking Intern</p>
<ul>
<li>Compiled, examined, and analyzed information for company projects, while researching and writing summary reports</li>
</ul>


<span class="test">
<p style="font-size: large; float: left; display: inline-block;">Pratt Institute & East China Normal University</p >
<p style="float: right; display: inline-block;">06-07/2016|New York, NY</p ></span>
<br/><br>
<p style="font-family: times, serif; font-size:11pt; font-style:italic;>Teaching Assistant & Resident Assistant</p>
<ul>
<li>Offered leading help in student advising, academic tutoring, conflict resolution in a Advanced Visual Art Program</li>
<li>Provided tutoring in the Computer Graphic Design and Design Seminar classes</li>
<li>Organized students to complete course projects, including the design of a brand book</li>
</ul>

<br>
<br>
<br>
<font size="5">Academic Experiences</font>
<span class="test">
<p style="font-size: large; float: left; display: inline-block;">The Closing Gap of Homeownership between Natives and Immigrants </p >
<p style="float: right; display: inline-block;">2018-2019|Richmond, VA</p ></span>
<br/><br>
<p style="font-family: times, serif; font-size:11pt; font-style:italic;>Researcher, Member of Math-Econ Honor Program</p>
<ul>
<li>Utilized data obtained from Current Population Survey to investigate how saving patterns of immigrants differs from those of the native citizens and driving factors for immigrants to buy houses</li>
<li>Constructed a logistic function and used R Studio to model the homeownership of immigrants and its relevance to factors such as race, year of immigration and household income</li>
</ul>

<p style="font-size: large; float: left; display: inline-block;">Data Visualization of Nanjing City’s Attractions[&nbsp;&nbsp;(click here to see)](https://alambyhe.github.io/math289/index.html)</p >
<p style="float: right; display: inline-block;">2018-2019|Richmond, VA</p ></span>
<br/><br>
<p style="font-family: times, serif; font-size:11pt; font-style:italic;>Independent Project, Introduction to Data Science Class</p>
<ul>
<li>Collected data from Wikipedia database using Python in order to design a website with a variety of information</li>
<li>Classified and analyzed the information using Cluster Analysis to increase visualization and characterization</li>
</ul>

<p style="font-size: large; float: left; display: inline-block;">US Election System</p >
<p style="float: right; display: inline-block;">05-07/2018|Richmond, VA</p ></span>
<br/><br>
<p style="font-family: times, serif; font-size:11pt; font-style:italic;>Assistant Researcher, Member of Arts & Sciences Research Fellowship</p>
<ul>
<li>Utilized statistical tests to show how the distribution of democrats can affect the role of states and the Electoral College</li>
<li>Made statistical decisions based on the simulated voting outcomes from the bootstrap algorithm with 10,000+ simulations</li>
</ul>


