---
title: "flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data("instacart")
set.seed(1)
plot1 =
  instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(
    x = ~aisle, y = ~n, type = "scatter", mode = "markers")
plot1
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
set.seed(1)
plot2 =
  instacart %>% 
  filter(product_name %in% c("Organic Half & Half","Organic Whole String Cheese","Organic Whole Strawberries","Coconut Water Kefir","Brown Rice") ) %>% 
  group_by(product_name) %>%
  plot_ly(y = ~order_hour_of_day, color = ~product_name, type = "box",
          colors = "Set2")
plot2
```

### Chart C

```{r}
set.seed(1)
plot2 =
  instacart %>% 
  mutate(
    user_id = as.character(user_id)
  ) %>% 
  count(user_id) %>% 
  top_n(20) %>% 
  plot_ly(x = ~user_id, y = ~n, color = ~user_id, type = "bar")
plot2
```

